name: hatch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/white_logo.png
    - assets/images/dragons_welcome.png
    - assets/images/color_logo.png
    - assets/images/coach_popup.png
  fonts:
    - family: BricolageGrotesqueBold
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Bold.ttf
    - family: BricolageGrotesqueMedium
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Medium.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf